# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  lat2:
    image: lat2
    build:
      context: .
      dockerfile: lat2/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 2000:2000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
